// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// stageFreqMC
NumericMatrix stageFreqMC(const NumericVector sampleTimes, const NumericMatrix sDur, const NumericVector mortRate);
RcppExport SEXP stageFreq_stageFreqMC(SEXP sampleTimesSEXP, SEXP sDurSEXP, SEXP mortRateSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericVector >::type sampleTimes(sampleTimesSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type sDur(sDurSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mortRate(mortRateSEXP);
    __result = Rcpp::wrap(stageFreqMC(sampleTimes, sDur, mortRate));
    return __result;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP stageFreq_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello_world());
    return __result;
END_RCPP
}
