# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Compute stage frequencies from simulated stage durations.
#' @param sampleTimes Vector of times at which the cohort was sampled.
#' @param sDur A matrix of stage durations where each row corresponds to the stage duration of an individual.
#'             If there is no exit from the last stage, the stage duration of that stage can be set to Inf.
#' @param mortRate A vector of mortality rates for each stage. Should be of length equal to the number of 
#'                 columns of sDur.
#' @return A matrix of stage counts. Each row gives the number of individuals in each stage for a given sampling time.             
#' @export
stageFreqMC <- function(sampleTimes, sDur, mortRate) {
    .Call('stageFreq_stageFreqMC', PACKAGE = 'stageFreq', sampleTimes, sDur, mortRate)
}

